name: Release To Maven Central Repository

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI Skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java Maven Release
        uses: qcastel/github-actions-maven-release@v1.12.32
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
        with:
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@microsphere.io"
          release-branch-name: "release"

          maven-args: "--batch-mode --update-snapshots -P release"
          maven-servers: ${{ secrets.MVN_REPO_SERVERS }}

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}